### ISSUE TITLE
Issue,PRのテンプレートの見直し

### ISSUE THREAD

**Issue by Izacchi16** [TechCafeFreedom/Wantum-android#11]
## 種類 (必須)

- 提案・議論

 ## 概要 (必須)

- 少し声が聞こえたのでこの辺りに関して話す必要がありそう

 ## リンク	

-

**Comment by b4tchkn** [comment]
PRはどうやって実装したと苦労したとこいらないかも？

**Comment by b4tchkn** [comment]
Issueは種類いらないと思う
あと
```
---
title: ''
labels: ''
assignees: ''

---
```
これも

**Comment by b4tchkn** [comment]
ちぇるがGitHub入ってきたからIssueに `# デザイン` ていう項目ほしいかも

**Comment by Izacchi16** [comment]
## 参考にした記事
これNoteに書けば良さそう？

**Comment by Izacchi16** [comment]
## どうやって実装した？
もコード見れば大丈夫そう
