### ISSUE TITLE
Navigationの導入

### ISSUE THREAD

**Issue by Izacchi16** [TechCafeFreedom/Wantum-android#5]
## 種類 (必須)
- 機能改善
 ## 概要 (必須)

- navgraphの作成など

 ## リンク	

-

**Comment by ho2ri2s** [comment]
navgraphの作成？とか、Navigationの導入っていう抽象的なISSUEで大丈夫！
authへの接続とかは、その担当者が各々やる感じにしよう！

**Comment by Izacchi16** [comment]
これMainActivityにBottomNavとか置く作業は別でIssue立てますか？

**Comment by ho2ri2s** [comment]
あー、どうだろう、確かにどこかに遷移するようにしないと動作確認できないしなあ〜
そんなに大変じゃないかもやし、お任せします！！
